schema_version: 2
id: broadside_citadel
name: Broadside Citadel
kind: ship
role: broadside_citadel
description: A capital linebreaker built around layered lateral batteries and a fortress spine.
views:
  horizontal:
    name: Horizontal
    axis: horizontal
    canonical_facing: right
    mirror_facing: left
    tiers:
    - id: full
      name: Full Detail
      sections:
      - id: capital_drive
        name: Capital Drive
        primary_property: thrusters
        secondary_properties:
        - reactor
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: seven_bell
          weight: 1
          cells:
          - '     '
          - ' ▄▶═ '
          - '▄▟▓▓ '
          - ▄███▓
          - '▄▜▓▓ '
          - ' ▄▶═ '
          - '     '
          color_mask:
          - SSSSS
          - SESSS
          - ESSSS
          - ESSSS
          - ESSSS
          - SESSS
          - SSSSS
        - id: armored
          weight: 1
          cells:
          - ' ▄▄═ '
          - '▄▶▓  '
          - ' ▟██▓'
          - ▄████
          - ▄███▓
          - ' ▜██▓'
          - ' ▄▄═ '
          color_mask:
          - SEESS
          - ESSSS
          - SSSSS
          - ESSSS
          - ESSSS
          - SSSSS
          - SEESS
      - id: drive_citadel
        name: Drive Citadel
        primary_property: armor
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: buttress
          weight: 1
          cells:
          - '     '
          - ▓│██═
          - ┌───┐
          - │▒◇▒│
          - └───┘
          - ▓│██═
          - '     '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
        - id: layered
          weight: 1
          cells:
          - ◢███◣
          - ▓███▓
          - █████
          - █▒▒▒█
          - █████
          - ▓███▓
          - ◥███◤
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
      - id: broadside_decks
        name: Broadside Decks
        primary_property: weapons
        secondary_properties:
        - hull
        - armor
        repeat:
          min: 1
          max: 10
        variants:
        - id: open_bays
          weight: 1
          cells:
          - ' ▀    '
          - ▓█▶▓█▶
          - ┌────┐
          - │▒◇▒▒│
          - └────┘
          - ▓█▶▓█▶
          - ' ▀    '
          color_mask:
          - SBSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SBSSSS
        - id: gunwalls
          weight: 1
          cells:
          - '▓███═ '
          - '─▓▙   '
          - ██████
          - █◇▒◇██
          - ██████
          - '─▓▛   '
          - '▓███═ '
          color_mask:
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
      - id: command_keep
        name: Command Keep
        primary_property: bridge
        secondary_properties:
        - sensors
        - screens
        repeat:
          min: 1
          max: 1
        variants:
        - id: tower
          weight: 1
          cells:
          - '  ▀  '
          - ' ┌─┐ '
          - ◢███◣
          - █☉███
          - █████
          - ◥███◤
          - '  ▾  '
          color_mask:
          - SSBSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
        - id: low_keep
          weight: 1
          cells:
          - '     '
          - ' ◢█◣ '
          - ◢███◣
          - █◇███
          - █████
          - ◥███◤
          - '     '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
      - id: siege_prow
        name: Siege Prow
        primary_property: main_gun
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 1
        variants:
        - id: triple
          weight: 1
          cells:
          - '      '
          - '      '
          - '─███▙ '
          - ─██▓▓▶
          - '─███▛ '
          - '      '
          - '      '
          color_mask:
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
        - id: ram
          weight: 1
          cells:
          - '      '
          - '  ◢█◣ '
          - ─████▙
          - ─███▓▶
          - ─████▛
          - '  ◥█◤ '
          - '      '
          color_mask:
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
      structure_lengths:
        capital_drive: 1
        drive_citadel: 1
        broadside_decks: 3
        command_keep: 1
        siege_prow: 1
    - id: medium
      name: Medium
      sections:
      - id: capital_drive
        name: Capital Drive
        primary_property: thrusters
        secondary_properties:
        - reactor
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: seven_bell
          weight: 1
          cells:
          - '    '
          - '▄▟▓ '
          - ▄██▓
          - ▄██▓
          - '▄▜▓ '
          color_mask:
          - SSSS
          - ESSS
          - ESSS
          - ESSS
          - ESSS
        - id: armored
          weight: 1
          cells:
          - '▄▶▓ '
          - ' ▟█▓'
          - ▄███
          - ▄██▓
          - ' ▜█▓'
          color_mask:
          - ESSS
          - SSSS
          - ESSS
          - ESSS
          - SSSS
      - id: drive_citadel
        name: Drive Citadel
        primary_property: armor
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: buttress
          weight: 1
          cells:
          - ' │  '
          - ┌──┐
          - │▒▒│
          - │▒◇│
          - └──┘
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: layered
          weight: 1
          cells:
          - ▓██▓
          - ████
          - █▒▒█
          - ████
          - ▓██▓
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      - id: broadside_decks
        name: Broadside Decks
        primary_property: weapons
        secondary_properties:
        - hull
        - armor
        repeat:
          min: 1
          max: 10
        variants:
        - id: open_bays
          weight: 1
          cells:
          - ▓█▶▓▶
          - ┌───┐
          - │▒◇▒│
          - └───┘
          - ▓█▶▓▶
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
        - id: gunwalls
          weight: 1
          cells:
          - '─▓▙  '
          - █████
          - █◇▒◇█
          - █████
          - '─▓▛  '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
      - id: command_keep
        name: Command Keep
        primary_property: bridge
        secondary_properties:
        - sensors
        - screens
        repeat:
          min: 1
          max: 1
        variants:
        - id: tower
          weight: 1
          cells:
          - ' ┌─ '
          - ◢██◣
          - █☉██
          - ████
          - ◥██◤
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: low_keep
          weight: 1
          cells:
          - ' ◢█ '
          - ◢██◣
          - █◇██
          - ████
          - ◥██◤
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      - id: siege_prow
        name: Siege Prow
        primary_property: main_gun
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 1
        variants:
        - id: triple
          weight: 1
          cells:
          - '     '
          - '─███ '
          - ─██▓▶
          - '─███ '
          - '     '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
        - id: ram
          weight: 1
          cells:
          - '  ◢█ '
          - ─███▙
          - ─███▶
          - ─███▛
          - '  ◥█ '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
      structure_lengths:
        capital_drive: 1
        drive_citadel: 1
        broadside_decks: 2
        command_keep: 1
        siege_prow: 1
    - id: compact
      name: Compact
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - ██
          - ▄█
          - ██
          color_mask:
          - SS
          - ES
          - SS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 15
        variants:
        - id: gunwall
          weight: 1
          cells:
          - █▶
          - ██
          - █▶
          color_mask:
          - SS
          - SS
          - SS
        - id: armor
          weight: 1
          cells:
          - ██
          - █◇
          - ██
          color_mask:
          - SS
          - SS
          - SS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: siege
          weight: 1
          cells:
          - ' ██'
          - ██▶
          - ' ██'
          color_mask:
          - SSS
          - SSS
          - SSS
      structure_lengths:
        drive: 1
        body: 6
        prow: 1
  vertical:
    name: Vertical
    axis: vertical
    canonical_facing: up
    mirror_facing: down
    tiers:
    - id: full
      name: Full Detail
      sections:
      - id: capital_drive
        name: Capital Drive
        primary_property: thrusters
        secondary_properties:
        - reactor
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: seven_bell
          weight: 1
          cells:
          - '      ▓▓▓▓    '
          - ▴▴  ▓▓████▓▓▴▴
          - '    ▄▄▄▄▄▄▄▄  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSEEEEEEEESS
        - id: armored
          weight: 1
          cells:
          - '    ▓▓██▓▓▓▓  '
          - ▄▄▓▓████████▄▄
          - '  ▄▄  ▄▄▄▄    '
          color_mask:
          - SSSSSSSSSSSSSS
          - EESSSSSSSSSSEE
          - SSEESSEEEESSSS
      - id: drive_citadel
        name: Drive Citadel
        primary_property: armor
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: buttress
          weight: 1
          cells:
          - ║║  ┌┌────┐┐║║
          - ██  ││▒▒◇◇││██
          - ▓▓  └└────┘┘▓▓
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: layered
          weight: 1
          cells:
          - ◢◢▓▓██████▓▓◣◣
          - ██████▒▒██████
          - ◥◥▓▓██████▓▓◤◤
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: broadside_decks
        name: Broadside Decks
        primary_property: weapons
        secondary_properties:
        - hull
        - armor
        repeat:
          min: 1
          max: 10
        variants:
        - id: open_bays
          weight: 1
          cells:
          - '  ▴▴┌┌──┐┐▴▴  '
          - '  ▓▓││▒▒││▓▓  '
          - ▀▀██││▒▒││██▶▶
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - BBSSSSSSSSSSSS
        - id: gunwalls
          weight: 1
          cells:
          - '    ██████    '
          - ██  ██◇◇██  ██
          - ██▓▓██◇◇██▓▓██
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: command_keep
        name: Command Keep
        primary_property: bridge
        secondary_properties:
        - sensors
        - screens
        repeat:
          min: 1
          max: 1
        variants:
        - id: tower
          weight: 1
          cells:
          - '    ◢◢████◣◣  '
          - ▀▀││████████▶▶
          - '    ◥◥████◤◤  '
          color_mask:
          - SSSSSSSSSSSSSS
          - BBSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: low_keep
          weight: 1
          cells:
          - '    ◢◢████◣◣  '
          - '  ██████████  '
          - '    ◥◥████◤◤  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: siege_prow
        name: Siege Prow
        primary_property: main_gun
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 1
        variants:
        - id: triple
          weight: 1
          cells:
          - '      ▴▴      '
          - '    ██▓▓██    '
          - '    ██████    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: ram
          weight: 1
          cells:
          - '    ▟▟▴▴▙▙    '
          - '  ██████████  '
          - '    ██████    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      structure_lengths:
        capital_drive: 1
        drive_citadel: 1
        broadside_decks: 9
        command_keep: 1
        siege_prow: 1
    - id: medium
      name: Medium
      sections:
      - id: capital_drive
        name: Capital Drive
        primary_property: thrusters
        secondary_properties:
        - reactor
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: seven_bell
          weight: 1
          cells:
          - '    ▓▓▓▓  '
          - '  ▜▜████▛▛'
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: armored
          weight: 1
          cells:
          - '  ▓▓██▓▓▓▓'
          - ▴▴▜▜████▛▛
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: drive_citadel
        name: Drive Citadel
        primary_property: armor
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: buttress
          weight: 1
          cells:
          - '  ┌┌────┐┐'
          - ──││▒▒▒▒││
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: layered
          weight: 1
          cells:
          - ▓▓██████▓▓
          - ████▒▒████
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: broadside_decks
        name: Broadside Decks
        primary_property: weapons
        secondary_properties:
        - hull
        - armor
        repeat:
          min: 1
          max: 10
        variants:
        - id: open_bays
          weight: 1
          cells:
          - ▴▴┌┌──┐┐▴▴
          - ▴▴││◇◇││▴▴
          - ▓▓└└──┘┘▓▓
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: gunwalls
          weight: 1
          cells:
          - '  ██████  '
          - ▟▟██▒▒██▙▙
          - ││██████││
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: command_keep
        name: Command Keep
        primary_property: bridge
        secondary_properties:
        - sensors
        - screens
        repeat:
          min: 1
          max: 1
        variants:
        - id: tower
          weight: 1
          cells:
          - '  ◢◢████◣◣'
          - └└██☉☉████
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: low_keep
          weight: 1
          cells:
          - '  ◢◢████◣◣'
          - ◥◥██◇◇████
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: siege_prow
        name: Siege Prow
        primary_property: main_gun
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 1
        variants:
        - id: triple
          weight: 1
          cells:
          - '    ▴▴    '
          - '  ██████  '
          - '  ││││││  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: ram
          weight: 1
          cells:
          - '  ▟▟▴▴▙▙  '
          - ◥◥██████◤◤
          - '  ││││││  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
          - SSSSSSSSSS
      structure_lengths:
        capital_drive: 1
        drive_citadel: 1
        broadside_decks: 10
        command_keep: 1
        siege_prow: 1
    - id: compact
      name: Compact
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - ██████
          color_mask:
          - SSSSSS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 15
        variants:
        - id: gunwall
          weight: 1
          cells:
          - ▴▴██▴▴
          color_mask:
          - SSSSSS
        - id: armor
          weight: 1
          cells:
          - ██◇◇██
          color_mask:
          - SSSSSS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: siege
          weight: 1
          cells:
          - ██▴▴██
          - '  ██  '
          color_mask:
          - SSSSSS
          - SSSSSS
      structure_lengths:
        drive: 1
        body: 15
        prow: 1
