schema_version: 2
id: falsehold_raider
name: Falsehold Raider
kind: ship
role: falsehold_raider
description: An armed merchant hull whose cargo seams conceal batteries and reinforced magazines.
views:
  horizontal:
    name: Horizontal
    axis: horizontal
    canonical_facing: right
    mirror_facing: left
    tiers:
    - id: full
      name: Full Detail
      sections:
      - id: merchant_drive
        name: Merchant Drive
        primary_property: thrusters
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: triple
          weight: 1
          cells:
          - '    '
          - ' ▄▶ '
          - '    '
          - ▄██▓
          - '    '
          - ' ▄▶ '
          - '    '
          color_mask:
          - SSSS
          - SESS
          - SSSS
          - ESSS
          - SSSS
          - SESS
          - SSSS
        - id: dirty
          weight: 1
          cells:
          - '    '
          - ' ▄▄ '
          - '▄▶▓ '
          - ▄██▓
          - '    '
          - ' ▄▶ '
          - '    '
          color_mask:
          - SSSS
          - SEES
          - ESSS
          - ESSS
          - SSSS
          - SESS
          - SSSS
      - id: armored_buttress
        name: Armored Buttress
        primary_property: armor
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: ribbed
          weight: 1
          cells:
          - '    '
          - ▓██═
          - ┌──┐
          - █▒▒█
          - └──┘
          - ▓██═
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: sealed
          weight: 1
          cells:
          - '    '
          - ◢██◣
          - ████
          - █░░█
          - ████
          - ◥██◤
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      - id: false_holds
        name: False Cargo Holds
        primary_property: cargo
        secondary_properties:
        - weapons
        - hull
        repeat:
          min: 1
          max: 8
        variants:
        - id: doors
          weight: 1
          cells:
          - '      '
          - ' ▀    '
          - ┌────┐
          - │▒◇▒▒│
          - └────┘
          - ' ▾    '
          - '      '
          color_mask:
          - SSSSSS
          - SBSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
        - id: containers
          weight: 1
          cells:
          - '      '
          - '      '
          - ◢████◣
          - █▒┤├▒█
          - ◥████◤
          - '      '
          - '      '
          color_mask:
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
      - id: masked_battery
        name: Masked Battery
        primary_property: weapons
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 1
        variants:
        - id: closed
          weight: 1
          cells:
          - '    '
          - '    '
          - ◢██◣
          - █≡██
          - ◥██◤
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: open
          weight: 1
          cells:
          - '    '
          - ' ▴  '
          - '▓█▶ '
          - ████
          - '▓█▶ '
          - ' ▾  '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      - id: merchant_prow
        name: Merchant Prow
        primary_property: hull
        secondary_properties:
        - main_gun
        repeat:
          min: 1
          max: 1
        variants:
        - id: blunt
          weight: 1
          cells:
          - '    '
          - '    '
          - '██▙ '
          - ██▓▶
          - '██▛ '
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: tapered
          weight: 1
          cells:
          - '    '
          - '    '
          - '▓█▙ '
          - ███▶
          - '▓█▛ '
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      structure_lengths:
        merchant_drive: 1
        armored_buttress: 1
        false_holds: 4
        masked_battery: 1
        merchant_prow: 1
    - id: medium
      name: Medium
      sections:
      - id: merchant_drive
        name: Merchant Drive
        primary_property: thrusters
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: triple
          weight: 1
          cells:
          - ' ▄ '
          - '   '
          - ▄█▓
          - '   '
          - ' ▄ '
          color_mask:
          - SES
          - SSS
          - ESS
          - SSS
          - SES
        - id: dirty
          weight: 1
          cells:
          - ' ▄ '
          - '▄▶ '
          - ▄█▓
          - '   '
          - ' ▄ '
          color_mask:
          - SES
          - ESS
          - ESS
          - SSS
          - SES
      - id: armored_buttress
        name: Armored Buttress
        primary_property: armor
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: ribbed
          weight: 1
          cells:
          - ▓█═
          - ┌─┐
          - █▒█
          - └─┘
          - ▓█═
          color_mask:
          - SSS
          - SSS
          - SSS
          - SSS
          - SSS
        - id: sealed
          weight: 1
          cells:
          - ◢█◣
          - ███
          - █░█
          - ███
          - ◥█◤
          color_mask:
          - SSS
          - SSS
          - SSS
          - SSS
          - SSS
      - id: false_holds
        name: False Cargo Holds
        primary_property: cargo
        secondary_properties:
        - weapons
        - hull
        repeat:
          min: 1
          max: 8
        variants:
        - id: doors
          weight: 1
          cells:
          - ' ▀   '
          - ┌───┐
          - │▒◇▒│
          - └───┘
          - ' ▾   '
          color_mask:
          - SBSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
        - id: containers
          weight: 1
          cells:
          - '     '
          - ◢███◣
          - █▒┤├█
          - ◥███◤
          - '     '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
      - id: masked_battery
        name: Masked Battery
        primary_property: weapons
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 1
        variants:
        - id: closed
          weight: 1
          cells:
          - '   '
          - ◢█◣
          - █≡█
          - ◥█◤
          - '   '
          color_mask:
          - SSS
          - SSS
          - SSS
          - SSS
          - SSS
        - id: open
          weight: 1
          cells:
          - ' ▴ '
          - '▓█ '
          - ███
          - '▓█ '
          - ' ▾ '
          color_mask:
          - SSS
          - SSS
          - SSS
          - SSS
          - SSS
      - id: merchant_prow
        name: Merchant Prow
        primary_property: hull
        secondary_properties:
        - main_gun
        repeat:
          min: 1
          max: 1
        variants:
        - id: blunt
          weight: 1
          cells:
          - '   '
          - '██ '
          - ██▶
          - '██ '
          - '   '
          color_mask:
          - SSS
          - SSS
          - SSS
          - SSS
          - SSS
        - id: tapered
          weight: 1
          cells:
          - '   '
          - '▓█ '
          - ██▶
          - '▓█ '
          - '   '
          color_mask:
          - SSS
          - SSS
          - SSS
          - SSS
          - SSS
      structure_lengths:
        merchant_drive: 1
        armored_buttress: 1
        false_holds: 3
        masked_battery: 1
        merchant_prow: 1
    - id: compact
      name: Compact
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - ' █'
          - ▄█
          - ' █'
          color_mask:
          - SS
          - ES
          - SS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 12
        variants:
        - id: hold
          weight: 1
          cells:
          - ██
          - █▒
          - ██
          color_mask:
          - SS
          - SS
          - SS
        - id: gun_hold
          weight: 1
          cells:
          - ▀█
          - █◇
          - ▄█
          color_mask:
          - SS
          - SS
          - SS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: prow
          weight: 1
          cells:
          - '   '
          - ██▶
          - '   '
          color_mask:
          - SSS
          - SSS
          - SSS
      structure_lengths:
        drive: 1
        body: 6
        prow: 1
  vertical:
    name: Vertical
    axis: vertical
    canonical_facing: up
    mirror_facing: down
    tiers:
    - id: full
      name: Full Detail
      sections:
      - id: merchant_drive
        name: Merchant Drive
        primary_property: thrusters
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: triple
          weight: 1
          cells:
          - '      ▓▓      '
          - '  ▄▄  ██  ▄▄  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSEESSSSSSEESS
        - id: dirty
          weight: 1
          cells:
          - '      ▓▓      '
          - '  ▄▄▴▴██  ▄▄  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSEESSSSSSEESS
      - id: armored_buttress
        name: Armored Buttress
        primary_property: armor
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: ribbed
          weight: 1
          cells:
          - '  ║║┌┌██┐┐║║  '
          - '  ██││▒▒││██  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: sealed
          weight: 1
          cells:
          - '  ◢◢██████◣◣  '
          - '  ████░░████  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: false_holds
        name: False Cargo Holds
        primary_property: cargo
        secondary_properties:
        - weapons
        - hull
        repeat:
          min: 1
          max: 8
        variants:
        - id: doors
          weight: 1
          cells:
          - '    ┌┌──┐┐    '
          - '    ││▒▒││    '
          - '  ▀▀││▒▒││▶▶  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSBBSSSSSSSSSS
        - id: containers
          weight: 1
          cells:
          - '    ◢◢██◣◣    '
          - '    ██┴┴██    '
          - '    ██▒▒██    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: masked_battery
        name: Masked Battery
        primary_property: weapons
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 1
        variants:
        - id: closed
          weight: 1
          cells:
          - '    ◢◢██◣◣    '
          - '    ██║║██    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: open
          weight: 1
          cells:
          - '      ██      '
          - '  ◀◀██████▶▶  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: merchant_prow
        name: Merchant Prow
        primary_property: hull
        secondary_properties:
        - main_gun
        repeat:
          min: 1
          max: 1
        variants:
        - id: blunt
          weight: 1
          cells:
          - '      ▴▴      '
          - '    ██████    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: tapered
          weight: 1
          cells:
          - '      ▴▴      '
          - '    ██████    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      structure_lengths:
        merchant_drive: 1
        armored_buttress: 1
        false_holds: 8
        masked_battery: 1
        merchant_prow: 1
    - id: medium
      name: Medium
      sections:
      - id: merchant_drive
        name: Merchant Drive
        primary_property: thrusters
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: triple
          weight: 1
          cells:
          - '    ▓▓    '
          - '    ▄▄    '
          color_mask:
          - SSSSSSSSSS
          - SSSSEESSSS
        - id: dirty
          weight: 1
          cells:
          - '    ▓▓    '
          - '  ▄▄▄▄    '
          color_mask:
          - SSSSSSSSSS
          - SSEEEESSSS
      - id: armored_buttress
        name: Armored Buttress
        primary_property: armor
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: ribbed
          weight: 1
          cells:
          - ║║┌┌██┐┐║║
          - ▓▓└└██┘┘▓▓
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: sealed
          weight: 1
          cells:
          - ◢◢██████◣◣
          - ◥◥██████◤◤
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: false_holds
        name: False Cargo Holds
        primary_property: cargo
        secondary_properties:
        - weapons
        - hull
        repeat:
          min: 1
          max: 8
        variants:
        - id: doors
          weight: 1
          cells:
          - '  ┌┌──┐┐  '
          - '  ││◇◇││  '
          - '  └└──┘┘  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: containers
          weight: 1
          cells:
          - '  ◢◢██◣◣  '
          - '  ██┬┬██  '
          - '  ◥◥██◤◤  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: masked_battery
        name: Masked Battery
        primary_property: weapons
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 1
        variants:
        - id: closed
          weight: 1
          cells:
          - '  ◢◢██◣◣  '
          - '  ◥◥██◤◤  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: open
          weight: 1
          cells:
          - '    ██    '
          - '  ▓▓██▓▓  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: merchant_prow
        name: Merchant Prow
        primary_property: hull
        secondary_properties:
        - main_gun
        repeat:
          min: 1
          max: 1
        variants:
        - id: blunt
          weight: 1
          cells:
          - '    ▴▴    '
          - '  ██████  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: tapered
          weight: 1
          cells:
          - '    ▴▴    '
          - '  ▓▓██▓▓  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      structure_lengths:
        merchant_drive: 1
        armored_buttress: 1
        false_holds: 8
        masked_battery: 1
        merchant_prow: 1
    - id: compact
      name: Compact
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - ██████
          color_mask:
          - SSSSSS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 12
        variants:
        - id: hold
          weight: 1
          cells:
          - ██▒▒██
          color_mask:
          - SSSSSS
        - id: gun_hold
          weight: 1
          cells:
          - ██◇◇██
          color_mask:
          - SSSSSS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: prow
          weight: 1
          cells:
          - '  ▴▴  '
          - '  ██  '
          color_mask:
          - SSSSSS
          - SSSSSS
      structure_lengths:
        drive: 1
        body: 12
        prow: 1
