schema_version: 2
id: junction_pinnace
name: Junction Pinnace
kind: ship
role: junction_pinnace
description: A tiny courier and landing craft wrapped around drive, compensator, and cabin.
views:
  horizontal:
    name: Horizontal
    axis: horizontal
    canonical_facing: right
    mirror_facing: left
    tiers:
    - id: full
      name: Full Detail
      structure_lengths:
        overdrive: 1
        sail_nodes: 1
        cabin: 3
        landing_nose: 1
      sections:
      - id: overdrive
        name: Overdrive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: single
          weight: 1
          cells:
          - '    '
          - '    '
          - ' ▀▀▓'
          - ' ▀█▓'
          - '    '
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SEES
          - SESS
          - SSSS
          - SSSS
          - SSSS
        - id: fork
          weight: 1
          cells:
          - '    '
          - ' ▀  '
          - ' ▀▶▓'
          - ' ▀▶▓'
          - '    '
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SESS
          - SESS
          - SESS
          - SSSS
          - SSSS
          - SSSS
      - id: sail_nodes
        name: Sail Nodes
        primary_property: spindrive
        secondary_properties:
        - radiator
        repeat:
          min: 1
          max: 1
        variants:
        - id: diamond
          weight: 1
          cells:
          - '    '
          - ▗▄▄▖
          - ▓██▓
          - ▓██▓
          - ▝▀▀▘
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: open
          weight: 1
          cells:
          - '    '
          - ' ◆  '
          - ▓██▓
          - ▓██▓
          - ' ◇  '
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      - id: cabin
        name: Cabin
        primary_property: habitat
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 3
        variants:
        - id: window
          weight: 1
          cells:
          - '    '
          - ' ▀  '
          - ╭──╮
          - █◆◆█
          - ╰──╯
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SBSS
          - SSSS
          - SWWS
          - SSSS
          - SSSS
          - SSSS
        - id: armored
          weight: 1
          cells:
          - '    '
          - '    '
          - ▗▄▄▖
          - █◆▒█
          - ▝▀▀▘
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SWSS
          - SSSS
          - SSSS
          - SSSS
      - id: landing_nose
        name: Landing Nose
        primary_property: utility
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: round
          weight: 1
          cells:
          - '   '
          - '   '
          - '◇▙ '
          - ◇█►
          - '◇▛ '
          - '   '
          - '   '
          color_mask:
          - SSS
          - SSS
          - DSS
          - DSS
          - DSS
          - SSS
          - SSS
        - id: probe
          weight: 1
          cells:
          - '   '
          - '   '
          - '◇▙ '
          - █◆►
          - '◇▛ '
          - '   '
          - '   '
          color_mask:
          - SSS
          - SSS
          - DSS
          - SWS
          - DSS
          - SSS
          - SSS
    - id: medium
      name: Medium
      structure_lengths:
        overdrive: 1
        sail_nodes: 1
        cabin: 3
        landing_nose: 1
      sections:
      - id: overdrive
        name: Overdrive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: single
          weight: 1
          cells:
          - '   '
          - ' ▀▓'
          - ' ▀▓'
          - '   '
          - '   '
          color_mask:
          - SSS
          - SES
          - SES
          - SSS
          - SSS
        - id: fork
          weight: 1
          cells:
          - ' ▀ '
          - ' ▀▓'
          - ' ▀▓'
          - '   '
          - '   '
          color_mask:
          - SES
          - SES
          - SES
          - SSS
          - SSS
      - id: sail_nodes
        name: Sail Nodes
        primary_property: spindrive
        secondary_properties:
        - radiator
        repeat:
          min: 1
          max: 1
        variants:
        - id: diamond
          weight: 1
          cells:
          - ▗▄▖
          - ▓█▓
          - ▓█▓
          - ▝▀▘
          - '   '
          color_mask:
          - SSS
          - SSS
          - SSS
          - SSS
          - SSS
        - id: open
          weight: 1
          cells:
          - ' ◆ '
          - ▓█▓
          - ▓█▓
          - ' ◇ '
          - '   '
          color_mask:
          - SSS
          - SSS
          - SSS
          - SSS
          - SSS
      - id: cabin
        name: Cabin
        primary_property: habitat
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 3
        variants:
        - id: window
          weight: 1
          cells:
          - ' ▀ '
          - ╭─╮
          - █◆█
          - ╰─╯
          - '   '
          color_mask:
          - SBS
          - SSS
          - SWS
          - SSS
          - SSS
        - id: armored
          weight: 1
          cells:
          - '   '
          - ▗▄▖
          - █◆█
          - ▝▀▘
          - '   '
          color_mask:
          - SSS
          - SSS
          - SWS
          - SSS
          - SSS
      - id: landing_nose
        name: Landing Nose
        primary_property: utility
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: round
          weight: 1
          cells:
          - '  '
          - '◇ '
          - ◇►
          - '◇ '
          - '  '
          color_mask:
          - SS
          - DS
          - DS
          - DS
          - SS
        - id: probe
          weight: 1
          cells:
          - '  '
          - '◇ '
          - █►
          - '◇ '
          - '  '
          color_mask:
          - SS
          - DS
          - SS
          - DS
          - SS
    - id: compact
      name: Compact
      structure_lengths:
        drive: 1
        body: 4
        prow: 1
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - '  '
          - ▀▓
          - '  '
          color_mask:
          - SS
          - ES
          - SS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 4
        variants:
        - id: cabin
          weight: 1
          cells:
          - ' ▀◆'
          - █◆█
          - ' ▄ '
          color_mask:
          - SBW
          - SWS
          - SSS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: nose
          weight: 1
          cells:
          - ' ◇'
          - ◇►
          - ' ◇'
          color_mask:
          - SD
          - DS
          - SD
  vertical:
    name: Vertical
    axis: vertical
    canonical_facing: up
    mirror_facing: down
    tiers:
    - id: full
      name: Full Detail
      structure_lengths:
        overdrive: 1
        sail_nodes: 1
        cabin: 3
        landing_nose: 1
      sections:
      - id: overdrive
        name: Overdrive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: single
          weight: 1
          cells:
          - '    ▓▓▓▓      '
          - '    ▌▌▌▌      '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSEEEESSSSSS
        - id: fork
          weight: 1
          cells:
          - '    ▓▓▓▓      '
          - '  ▌▌▌▌▌▌      '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSEEEEEESSSSSS
      - id: sail_nodes
        name: Sail Nodes
        primary_property: spindrive
        secondary_properties:
        - radiator
        repeat:
          min: 1
          max: 1
        variants:
        - id: diamond
          weight: 1
          cells:
          - '  ▗▗▓▓▓▓▖▖    '
          - '  ▐▐████▌▌    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: open
          weight: 1
          cells:
          - '    ▓▓▓▓      '
          - '  ◆◆████◇◇    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: cabin
        name: Cabin
        primary_property: habitat
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 3
        variants:
        - id: window
          weight: 1
          cells:
          - '    ╭╭██╮╮    '
          - '  ▌▌││◆◆││    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSBBSSWWSSSSSS
        - id: armored
          weight: 1
          cells:
          - '    ▗▗██▖▖    '
          - '    ▐▐◆◆▌▌    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSWWSSSSSS
      - id: landing_nose
        name: Landing Nose
        primary_property: utility
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: round
          weight: 1
          cells:
          - '      ▲▲      '
          - '    ◇◇◇◇◇◇    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSDDDDDDSSSS
        - id: probe
          weight: 1
          cells:
          - '      ▲▲      '
          - '    ◇◇██◇◇    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSDDSSDDSSSS
    - id: medium
      name: Medium
      structure_lengths:
        overdrive: 1
        sail_nodes: 1
        cabin: 3
        landing_nose: 1
      sections:
      - id: overdrive
        name: Overdrive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: single
          weight: 1
          cells:
          - '  ▓▓▓▓    '
          - '          '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: fork
          weight: 1
          cells:
          - '  ▓▓▓▓    '
          - '          '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: sail_nodes
        name: Sail Nodes
        primary_property: spindrive
        secondary_properties:
        - radiator
        repeat:
          min: 1
          max: 1
        variants:
        - id: diamond
          weight: 1
          cells:
          - '▗▗▓▓▓▓▖▖  '
          - '▝▝▓▓▓▓▘▘  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: open
          weight: 1
          cells:
          - '  ▓▓▓▓    '
          - '  ▓▓▓▓    '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: cabin
        name: Cabin
        primary_property: habitat
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 3
        variants:
        - id: window
          weight: 1
          cells:
          - '  ╭╭██╮╮  '
          - '  ╰╰██╯╯  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: armored
          weight: 1
          cells:
          - '  ▗▗██▖▖  '
          - '  ▝▝██▘▘  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: landing_nose
        name: Landing Nose
        primary_property: utility
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: round
          weight: 1
          cells:
          - '    ▲▲    '
          color_mask:
          - SSSSSSSSSS
        - id: probe
          weight: 1
          cells:
          - '    ▲▲    '
          color_mask:
          - SSSSSSSSSS
    - id: compact
      name: Compact
      structure_lengths:
        drive: 1
        body: 4
        prow: 1
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - '  ▓▓  '
          color_mask:
          - SSSSSS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 4
        variants:
        - id: cabin
          weight: 1
          cells:
          - '◆◆██  '
          - '  ██  '
          color_mask:
          - WWSSSS
          - SSSSSS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: nose
          weight: 1
          cells:
          - ◇◇▲▲◇◇
          color_mask:
          - DDSSDD
