schema_version: 2
id: needle_picket
name: Needle Picket
kind: ship
role: needle_picket
description: A lean independent patrol hull with exposed drive nodes and an oversized sensor prow.
views:
  horizontal:
    name: Horizontal
    axis: horizontal
    canonical_facing: right
    mirror_facing: left
    tiers:
    - id: full
      name: Full Detail
      structure_lengths:
        thrusters: 1
        drive_nodes: 1
        patrol_spine: 7
        sensor_crown: 1
        needle: 1
      sections:
      - id: thrusters
        name: Thruster Fork
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: fork
          weight: 1
          cells:
          - '     '
          - ' ▄╺▀ '
          - '▄▖█▓ '
          - '▄██▓ '
          - '▄▘█▓ '
          - '     '
          - '     '
          color_mask:
          - SSSSS
          - SESES
          - ESSSS
          - ESSSS
          - ESSSS
          - SSSSS
          - SSSSS
        - id: split
          weight: 1
          cells:
          - '     '
          - ' ▄   '
          - '▄▘▀▓ '
          - ' ▄██▓'
          - '▄▖▀▓ '
          - '     '
          - '     '
          color_mask:
          - SSSSS
          - SESSS
          - ESESS
          - SESSS
          - ESESS
          - SSSSS
          - SSSSS
      - id: drive_nodes
        name: Drive Nodes
        primary_property: spindrive
        secondary_properties:
        - radiator
        repeat:
          min: 1
          max: 1
        variants:
        - id: open
          weight: 1
          cells:
          - '    '
          - ' ☼  '
          - ▓██═
          - █░██
          - ▓██═
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SBSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: veiled
          weight: 1
          cells:
          - '    '
          - ' ▀  '
          - ╭██╮
          - █▒██
          - ╰██╯
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SBSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      - id: patrol_spine
        name: Patrol Spine
        primary_property: hull
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 7
        variants:
        - id: sensor_rib
          weight: 1
          cells:
          - '    '
          - ' ▀  '
          - ╭──╮
          - █░◇█
          - ╰──╯
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SBSS
          - SSSS
          - SSWS
          - SSSS
          - SSSS
          - SSSS
        - id: plain_rib
          weight: 1
          cells:
          - '    '
          - '    '
          - ▗▄▄▖
          - █▒░█
          - ▝▀▀▘
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      - id: sensor_crown
        name: Sensor Crown
        primary_property: sensors
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: crown
          weight: 1
          cells:
          - '    '
          - ' ☼█☼'
          - ◇█◆█
          - ☼██☼
          - ' ◥█◤'
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SBSB
          - SSWS
          - BSSB
          - SSSS
          - SSSS
          - SSSS
        - id: dish
          weight: 1
          cells:
          - '    '
          - '  ▀ '
          - ╭██╮
          - ☼█◆█
          - ╰██╯
          - '    '
          - '    '
          color_mask:
          - SSSS
          - SSBS
          - SSSS
          - BSWS
          - SSSS
          - SSSS
          - SSSS
      - id: needle
        name: Needle Prow
        primary_property: main_gun
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 1
        variants:
        - id: long
          weight: 1
          cells:
          - '     '
          - '     '
          - '  ╾▙ '
          - ╺═▓▀►
          - '  ╾▛ '
          - '     '
          - '     '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSAA
          - SSSSS
          - SSSSS
          - SSSSS
        - id: probe
          weight: 1
          cells:
          - '     '
          - '     '
          - '  ─▙ '
          - ╺██▀►
          - '  ─▛ '
          - '     '
          - '     '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSAA
          - SSSSS
          - SSSSS
          - SSSSS
    - id: medium
      name: Medium
      structure_lengths:
        thrusters: 1
        drive_nodes: 1
        patrol_spine: 7
        sensor_crown: 1
        needle: 1
      sections:
      - id: thrusters
        name: Thruster Fork
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: fork
          weight: 1
          cells:
          - ' ▄╺ '
          - '▄▖█ '
          - '▄██ '
          - '▄▘█ '
          - '    '
          color_mask:
          - SESS
          - ESSS
          - ESSS
          - ESSS
          - SSSS
        - id: split
          weight: 1
          cells:
          - ' ▄  '
          - '▄▘▀ '
          - ' ▄█▓'
          - '▄▖▀ '
          - '    '
          color_mask:
          - SESS
          - ESES
          - SESS
          - ESES
          - SSSS
      - id: drive_nodes
        name: Drive Nodes
        primary_property: spindrive
        secondary_properties:
        - radiator
        repeat:
          min: 1
          max: 1
        variants:
        - id: open
          weight: 1
          cells:
          - ' ☼ '
          - ▓█═
          - █░█
          - ▓█═
          - '   '
          color_mask:
          - SBS
          - SSS
          - SSS
          - SSS
          - SSS
        - id: veiled
          weight: 1
          cells:
          - ' ▀ '
          - ╭█╮
          - █▒█
          - ╰█╯
          - '   '
          color_mask:
          - SBS
          - SSS
          - SSS
          - SSS
          - SSS
      - id: patrol_spine
        name: Patrol Spine
        primary_property: hull
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 7
        variants:
        - id: sensor_rib
          weight: 1
          cells:
          - ' ▀ '
          - ╭─╮
          - █░█
          - ╰─╯
          - '   '
          color_mask:
          - SBS
          - SSS
          - SSS
          - SSS
          - SSS
        - id: plain_rib
          weight: 1
          cells:
          - '   '
          - ▗▄▖
          - █▒█
          - ▝▀▘
          - '   '
          color_mask:
          - SSS
          - SSS
          - SSS
          - SSS
          - SSS
      - id: sensor_crown
        name: Sensor Crown
        primary_property: sensors
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: crown
          weight: 1
          cells:
          - ' ☼☼'
          - ◇██
          - ☼█☼
          - ' ◥◤'
          - '   '
          color_mask:
          - SBB
          - SSS
          - BSB
          - SSS
          - SSS
        - id: dish
          weight: 1
          cells:
          - '   '
          - ╭█╮
          - ☼██
          - ╰█╯
          - '   '
          color_mask:
          - SSS
          - SSS
          - BSS
          - SSS
          - SSS
      - id: needle
        name: Needle Prow
        primary_property: main_gun
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 1
        variants:
        - id: long
          weight: 1
          cells:
          - '    '
          - '  ╾ '
          - ╺═▓►
          - '  ╾ '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSA
          - SSSS
          - SSSS
        - id: probe
          weight: 1
          cells:
          - '    '
          - '  ─ '
          - ╺██►
          - '  ─ '
          - '    '
          color_mask:
          - SSSS
          - SSSS
          - SSSA
          - SSSS
          - SSSS
    - id: compact
      name: Compact
      structure_lengths:
        drive: 1
        body: 6
        prow: 1
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - '  '
          - ▀█
          - '  '
          color_mask:
          - SS
          - ES
          - SS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 12
        variants:
        - id: spine
          weight: 1
          cells:
          - ' ▴'
          - ██
          - '  '
          color_mask:
          - SS
          - SS
          - SS
        - id: sensor
          weight: 1
          cells:
          - ' ▀'
          - █☼
          - '  '
          color_mask:
          - SB
          - SB
          - SS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: needle
          weight: 1
          cells:
          - '   '
          - ─▀►
          - '   '
          color_mask:
          - SSS
          - SAA
          - SSS
  vertical:
    name: Vertical
    axis: vertical
    canonical_facing: up
    mirror_facing: down
    tiers:
    - id: full
      name: Full Detail
      structure_lengths:
        thrusters: 1
        drive_nodes: 1
        patrol_spine: 7
        sensor_crown: 1
        needle: 1
      sections:
      - id: thrusters
        name: Thruster Fork
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: fork
          weight: 1
          cells:
          - '              '
          - '  ╹╹██████    '
          - '    ▐▐▐▐▐▐    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSEEEEEESSSS
        - id: split
          weight: 1
          cells:
          - '      ▓▓      '
          - '    ▌▌██▌▌    '
          - '    ▐▐  ▐▐    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSEESSEESSSS
          - SSSSEESSEESSSS
      - id: drive_nodes
        name: Drive Nodes
        primary_property: spindrive
        secondary_properties:
        - radiator
        repeat:
          min: 1
          max: 1
        variants:
        - id: open
          weight: 1
          cells:
          - '    ║║██║║    '
          - '  ☼☼██░░██    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSBBSSSSSSSSSS
        - id: veiled
          weight: 1
          cells:
          - '    ╭╭██╮╮    '
          - '  ▌▌██▒▒██    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSBBSSSSSSSSSS
      - id: patrol_spine
        name: Patrol Spine
        primary_property: hull
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 7
        variants:
        - id: sensor_rib
          weight: 1
          cells:
          - '    ╭╭██╮╮    '
          - '  ▌▌││░░││    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSBBSSSSSSSSSS
        - id: plain_rib
          weight: 1
          cells:
          - '    ▗▗██▖▖    '
          - '    ▐▐▒▒▌▌    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: sensor_crown
        name: Sensor Crown
        primary_property: sensors
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: crown
          weight: 1
          cells:
          - '  ☼☼██☼☼◣◣    '
          - '  ☼☼████◤◤    '
          color_mask:
          - SSBBSSBBSSSSSS
          - SSBBSSSSSSSSSS
        - id: dish
          weight: 1
          cells:
          - '    ╭╭██╮╮    '
          - '    ██████    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: needle
        name: Needle Prow
        primary_property: main_gun
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 1
        variants:
        - id: long
          weight: 1
          cells:
          - '      ▲▲      '
          - '    ╽╽▓▓╽╽    '
          - '      ╹╹      '
          color_mask:
          - SSSSSSAASSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: probe
          weight: 1
          cells:
          - '      ▲▲      '
          - '    ││██││    '
          - '      ╹╹      '
          color_mask:
          - SSSSSSAASSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
    - id: medium
      name: Medium
      structure_lengths:
        thrusters: 1
        drive_nodes: 1
        patrol_spine: 7
        sensor_crown: 1
        needle: 1
      sections:
      - id: thrusters
        name: Thruster Fork
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: fork
          weight: 1
          cells:
          - '          '
          - '▐▐▗▗██▖▖  '
          color_mask:
          - SSSSSSSSSS
          - EESSSSSSSS
        - id: split
          weight: 1
          cells:
          - '    ▓▓    '
          - '▐▐▖▖▐▐▗▗  '
          color_mask:
          - SSSSSSSSSS
          - EESSEESSSS
      - id: drive_nodes
        name: Drive Nodes
        primary_property: spindrive
        secondary_properties:
        - radiator
        repeat:
          min: 1
          max: 1
        variants:
        - id: open
          weight: 1
          cells:
          - '  ║║██║║  '
          - '  ▓▓██▓▓  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: veiled
          weight: 1
          cells:
          - '  ╭╭██╮╮  '
          - '  ╰╰██╯╯  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: patrol_spine
        name: Patrol Spine
        primary_property: hull
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 7
        variants:
        - id: sensor_rib
          weight: 1
          cells:
          - '  ╭╭██╮╮  '
          - '  ╰╰██╯╯  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: plain_rib
          weight: 1
          cells:
          - '  ▗▗██▖▖  '
          - '  ▝▝██▘▘  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: sensor_crown
        name: Sensor Crown
        primary_property: sensors
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: crown
          weight: 1
          cells:
          - '☼☼██☼☼◣◣  '
          - '  ◇◇☼☼    '
          color_mask:
          - BBSSBBSSSS
          - SSSSBBSSSS
        - id: dish
          weight: 1
          cells:
          - '  ╭╭██╮╮  '
          - '  ╰╰☼☼╯╯  '
          color_mask:
          - SSSSSSSSSS
          - SSSSBBSSSS
      - id: needle
        name: Needle Prow
        primary_property: main_gun
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 1
        variants:
        - id: long
          weight: 1
          cells:
          - '    ▲▲    '
          - '    ║║    '
          color_mask:
          - SSSSAASSSS
          - SSSSSSSSSS
        - id: probe
          weight: 1
          cells:
          - '    ▲▲    '
          - '    ██    '
          color_mask:
          - SSSSAASSSS
          - SSSSSSSSSS
    - id: compact
      name: Compact
      structure_lengths:
        drive: 1
        body: 6
        prow: 1
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - '  ██  '
          color_mask:
          - SSSSSS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 12
        variants:
        - id: spine
          weight: 1
          cells:
          - '◀◀██  '
          color_mask:
          - SSSSSS
        - id: sensor
          weight: 1
          cells:
          - '▌▌☼☼  '
          color_mask:
          - BBBBSS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: needle
          weight: 1
          cells:
          - '  ▲▲  '
          - '  ││  '
          color_mask:
          - SSAASS
          - SSSSSS
