schema_version: 2
id: pearl_shell
name: Pearl Shell
kind: ship
role: pearl_shell
description: An alien troop shell with offset carapace plates and a ring of recessed weapon ports.
views:
  horizontal:
    name: Horizontal
    axis: horizontal
    canonical_facing: right
    mirror_facing: left
    tiers:
    - id: full
      name: Full Detail
      sections:
      - id: ciliary_drive
        name: Ciliary Drive
        primary_property: thrusters
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: fan
          weight: 1
          cells:
          - ' ▄▄ '
          - '▄◢▓ '
          - ▄██▓
          - ▄██▓
          - '▄◥▓ '
          - '    '
          - ' ▄  '
          color_mask:
          - SEES
          - ESSS
          - ESSS
          - ESSS
          - ESSS
          - SSSS
          - SESS
        - id: barbs
          weight: 1
          cells:
          - ' ▄▶ '
          - '▄▟▓ '
          - ▄██▓
          - ▄▒█▓
          - '▄▜▓ '
          - '    '
          - ' ▄▶ '
          color_mask:
          - SESS
          - ESSS
          - ESSS
          - ESSS
          - ESSS
          - SSSS
          - SESS
      - id: rear_carapace
        name: Rear Carapace
        primary_property: armor
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: pearl
          weight: 1
          cells:
          - ' ◢██◣'
          - ◢████
          - █████
          - █▒◇██
          - █████
          - ◥████
          - ' ◥██◤'
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
        - id: scarred
          weight: 1
          cells:
          - '  ◢█◣'
          - ◢██▒█
          - ██◇██
          - █▒▒██
          - █████
          - ◥██▒█
          - '  ◥█◤'
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
      - id: weapon_ring
        name: Weapon Ring
        primary_property: weapons
        secondary_properties:
        - hangar
        - hull
        repeat:
          min: 1
          max: 5
        variants:
        - id: ports
          weight: 1
          cells:
          - ' ▀    '
          - ◢████◣
          - █◇█◇██
          - ██☉███
          - █◇██◇█
          - ◥████◤
          - '   ▾  '
          color_mask:
          - SBSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
        - id: sealed
          weight: 1
          cells:
          - '      '
          - ' ◢██◣ '
          - ◢████◣
          - █▒◊▒██
          - ◥████◤
          - ' ◥██◤ '
          - '      '
          color_mask:
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
          - SSSSSS
      - id: troop_lobe
        name: Troop Lobe
        primary_property: hangar
        secondary_properties:
        - habitat
        repeat:
          min: 1
          max: 1
        variants:
        - id: open
          weight: 1
          cells:
          - ' ◢██◣'
          - ◢█◇██
          - █████
          - ██☉██
          - █████
          - ◥██▒█
          - '  ◥█◤'
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
        - id: heavy
          weight: 1
          cells:
          - '  ◢█◣'
          - ◢████
          - █▒▒██
          - ██◇██
          - █████
          - ◥████
          - ' ◥██◤'
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
      - id: beak
        name: Carapace Beak
        primary_property: screens
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 1
        variants:
        - id: hook
          weight: 1
          cells:
          - '     '
          - ' ◢█◣ '
          - ◢███▙
          - ██◇▓▶
          - ◥███▛
          - '  ◥█ '
          - '     '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
        - id: round
          weight: 1
          cells:
          - '     '
          - '  ◢█◣'
          - ◢████
          - ██☉▓▶
          - ◥████
          - '  ◥█◤'
          - '     '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
      structure_lengths:
        ciliary_drive: 1
        rear_carapace: 1
        weapon_ring: 3
        troop_lobe: 1
        beak: 1
    - id: medium
      name: Medium
      sections:
      - id: ciliary_drive
        name: Ciliary Drive
        primary_property: thrusters
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: fan
          weight: 1
          cells:
          - '▄◢ '
          - ▄█▓
          - ▄█▓
          - '▄◥ '
          - '   '
          color_mask:
          - ESS
          - ESS
          - ESS
          - ESS
          - SSS
        - id: barbs
          weight: 1
          cells:
          - '▄▟ '
          - ▄█▓
          - ▄▒▓
          - '▄▜ '
          - '   '
          color_mask:
          - ESS
          - ESS
          - ESS
          - ESS
          - SSS
      - id: rear_carapace
        name: Rear Carapace
        primary_property: armor
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: pearl
          weight: 1
          cells:
          - ◢███
          - ████
          - █▒◇█
          - ████
          - ◥███
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: scarred
          weight: 1
          cells:
          - ◢███
          - ██◇█
          - █▒▒█
          - ████
          - ◥███
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      - id: weapon_ring
        name: Weapon Ring
        primary_property: weapons
        secondary_properties:
        - hangar
        - hull
        repeat:
          min: 1
          max: 5
        variants:
        - id: ports
          weight: 1
          cells:
          - ◢███◣
          - █◇█◇█
          - ██☉██
          - █◇███
          - ◥███◤
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
        - id: sealed
          weight: 1
          cells:
          - ' ◢██ '
          - ◢███◣
          - █▒◊▒█
          - ◥███◤
          - ' ◥██ '
          color_mask:
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
          - SSSSS
      - id: troop_lobe
        name: Troop Lobe
        primary_property: hangar
        secondary_properties:
        - habitat
        repeat:
          min: 1
          max: 1
        variants:
        - id: open
          weight: 1
          cells:
          - ◢█◇█
          - ████
          - ██☉█
          - ████
          - ◥███
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: heavy
          weight: 1
          cells:
          - ◢███
          - █▒▒█
          - ██◇█
          - ████
          - ◥███
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      - id: beak
        name: Carapace Beak
        primary_property: screens
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 1
        variants:
        - id: hook
          weight: 1
          cells:
          - ' ◢█ '
          - ◢██▙
          - ██◇▶
          - ◥██▛
          - '  ◥ '
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
        - id: round
          weight: 1
          cells:
          - '  ◢◣'
          - ◢███
          - ██☉▶
          - ◥███
          - '  ◥◤'
          color_mask:
          - SSSS
          - SSSS
          - SSSS
          - SSSS
          - SSSS
      structure_lengths:
        ciliary_drive: 1
        rear_carapace: 1
        weapon_ring: 3
        troop_lobe: 1
        beak: 1
    - id: compact
      name: Compact
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - ' █'
          - ▄█
          - ' ▾'
          color_mask:
          - SS
          - ES
          - SS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 10
        variants:
        - id: shell
          weight: 1
          cells:
          - ◢█
          - █◇
          - ◥█
          color_mask:
          - SS
          - SS
          - SS
        - id: ports
          weight: 1
          cells:
          - ▀█
          - █☉
          - ▄█
          color_mask:
          - SS
          - SS
          - SS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: beak
          weight: 1
          cells:
          - ' ◢ '
          - ██▶
          - ' ◥ '
          color_mask:
          - SSS
          - SSS
          - SSS
      structure_lengths:
        drive: 1
        body: 6
        prow: 1
  vertical:
    name: Vertical
    axis: vertical
    canonical_facing: up
    mirror_facing: down
    tiers:
    - id: full
      name: Full Detail
      sections:
      - id: ciliary_drive
        name: Ciliary Drive
        primary_property: thrusters
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: fan
          weight: 1
          cells:
          - '    ▓▓▓▓      '
          - ▄▄◥◥████◤◤  ▄▄
          color_mask:
          - SSSSSSSSSSSSSS
          - EESSSSSSSSSSEE
        - id: barbs
          weight: 1
          cells:
          - '    ▓▓▓▓      '
          - ▄▄▜▜██▒▒▛▛  ▄▄
          color_mask:
          - SSSSSSSSSSSSSS
          - EESSSSSSSSSSEE
      - id: rear_carapace
        name: Rear Carapace
        primary_property: armor
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: pearl
          weight: 1
          cells:
          - ◢◢██████████◣◣
          - ██████◇◇██████
          - '  ◥◥██████◤◤  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: scarred
          weight: 1
          cells:
          - ◢◢██████████◣◣
          - ◥◥██◇◇▒▒████◤◤
          - '  ◥◥██████◤◤  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: weapon_ring
        name: Weapon Ring
        primary_property: weapons
        secondary_properties:
        - hangar
        - hull
        repeat:
          min: 1
          max: 5
        variants:
        - id: ports
          weight: 1
          cells:
          - '  ◢◢██████◣◣  '
          - '  ██◇◇██████▶▶'
          - '▀▀██◇◇██◇◇██  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - BBSSSSSSSSSSSS
        - id: sealed
          weight: 1
          cells:
          - '    ◢◢██◣◣    '
          - '  ████▒▒████  '
          - '  ◥◥██▒▒██◤◤  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: troop_lobe
        name: Troop Lobe
        primary_property: hangar
        secondary_properties:
        - habitat
        repeat:
          min: 1
          max: 1
        variants:
        - id: open
          weight: 1
          cells:
          - ◢◢██████████◣◣
          - ██◇◇██☉☉████◤◤
          - '  ◥◥██████◤◤  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: heavy
          weight: 1
          cells:
          - ◢◢██████████◣◣
          - ◥◥██▒▒◇◇██████
          - '  ◥◥██████◤◤  '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      - id: beak
        name: Carapace Beak
        primary_property: screens
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 1
        variants:
        - id: hook
          weight: 1
          cells:
          - '    ▟▟▴▴▙▙    '
          - '  ████◇◇██◤◤  '
          - '    ◥◥██◤◤    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
        - id: round
          weight: 1
          cells:
          - '  ◢◢██▴▴██◣◣  '
          - '  ◥◥██☉☉██◤◤  '
          - '    ◥◥██◤◤    '
          color_mask:
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
          - SSSSSSSSSSSSSS
      structure_lengths:
        ciliary_drive: 1
        rear_carapace: 1
        weapon_ring: 5
        troop_lobe: 1
        beak: 1
    - id: medium
      name: Medium
      sections:
      - id: ciliary_drive
        name: Ciliary Drive
        primary_property: thrusters
        secondary_properties:
        - spindrive
        repeat:
          min: 1
          max: 1
        variants:
        - id: fan
          weight: 1
          cells:
          - '  ▓▓▓▓    '
          - '▄▄▄▄▄▄▄▄  '
          color_mask:
          - SSSSSSSSSS
          - EEEEEEEESS
        - id: barbs
          weight: 1
          cells:
          - '  ▓▓▓▓    '
          - '▄▄▄▄▄▄▄▄  '
          color_mask:
          - SSSSSSSSSS
          - EEEEEEEESS
      - id: rear_carapace
        name: Rear Carapace
        primary_property: armor
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: pearl
          weight: 1
          cells:
          - ██████████
          - ████▒▒████
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: scarred
          weight: 1
          cells:
          - ██████████
          - ████▒▒████
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: weapon_ring
        name: Weapon Ring
        primary_property: weapons
        secondary_properties:
        - hangar
        - hull
        repeat:
          min: 1
          max: 5
        variants:
        - id: ports
          weight: 1
          cells:
          - ◢◢██████◣◣
          - ████☉☉████
          - ◥◥██████◤◤
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: sealed
          weight: 1
          cells:
          - '  ◢◢██◣◣  '
          - ████◊◊████
          - '  ◥◥██◤◤  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: troop_lobe
        name: Troop Lobe
        primary_property: hangar
        secondary_properties:
        - habitat
        repeat:
          min: 1
          max: 1
        variants:
        - id: open
          weight: 1
          cells:
          - ██████████
          - ██████████
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: heavy
          weight: 1
          cells:
          - ██████████
          - ██▒▒██████
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      - id: beak
        name: Carapace Beak
        primary_property: screens
        secondary_properties:
        - sensors
        repeat:
          min: 1
          max: 1
        variants:
        - id: hook
          weight: 1
          cells:
          - '  ▟▟▴▴▙▙  '
          - '◥◥██████  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
        - id: round
          weight: 1
          cells:
          - ◢◢██▴▴██◣◣
          - '  ██████  '
          color_mask:
          - SSSSSSSSSS
          - SSSSSSSSSS
      structure_lengths:
        ciliary_drive: 1
        rear_carapace: 1
        weapon_ring: 5
        troop_lobe: 1
        beak: 1
    - id: compact
      name: Compact
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - ████▶▶
          color_mask:
          - SSSSSS
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 10
        variants:
        - id: shell
          weight: 1
          cells:
          - ██◇◇██
          color_mask:
          - SSSSSS
        - id: ports
          weight: 1
          cells:
          - ██☉☉██
          color_mask:
          - SSSSSS
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: beak
          weight: 1
          cells:
          - '  ▴▴  '
          - '  ██  '
          color_mask:
          - SSSSSS
          - SSSSSS
      structure_lengths:
        drive: 1
        body: 10
        prow: 1
