schema_version: 1
id: radiant_lance
name: Radiant Lance
kind: ship
role: radiant_lance
description: A glittering military spine with folding diamond radiators and petal
  habitats.
views:
  horizontal:
    name: Horizontal
    axis: horizontal
    canonical_facing: right
    mirror_facing: left
    tiers:
    - id: full
      name: Full Detail
      sections:
      - id: fusion_bell
        name: Fusion Bell
        primary_property: thrusters
        secondary_properties:
        - reactor
        repeat:
          min: 1
          max: 1
        variants:
        - id: focused
          weight: 1
          cells:
          - ' y▶═'
          - '    '
          - ' y▓ '
          - y██▓
          - ' y▓ '
          - '    '
          - ' y▶═'
        - id: hot
          weight: 1
          cells:
          - ' yy═'
          - ' y  '
          - 'y▟▓ '
          - y██▓
          - 'y▜▓ '
          - ' y  '
          - ' yy═'
      - id: engine_swell
        name: Engine Swell
        primary_property: spindrive
        secondary_properties:
        - reactor
        repeat:
          min: 1
          max: 1
        variants:
        - id: swell
          weight: 1
          cells:
          - ' ▴  '
          - ◢██◣
          - ▓██▓
          - █▒▒█
          - ▓██▓
          - ◥██◤
          - ' ▾  '
        - id: veined
          weight: 1
          cells:
          - ' R  '
          - ◢█◇◣
          - ▓██▓
          - █▒▒█
          - ▓██▓
          - ◥█◇◤
          - ' ▾  '
      - id: diamond_radiators
        name: Diamond Radiators
        primary_property: radiator
        secondary_properties:
        - hull
        repeat:
          min: 1
          max: 6
        variants:
        - id: open
          weight: 1
          cells:
          - '◢█◣ '
          - ' ╲  '
          - ┌──┐
          - │▒▒│
          - └──┘
          - ' ╱  '
          - '◥█◤ '
        - id: folded
          weight: 1
          cells:
          - ' ▴  '
          - ' │  '
          - ┌──┐
          - │◇▒│
          - └──┘
          - ' │  '
          - ' ▾  '
      - id: habitat_petals
        name: Habitat Petals
        primary_property: habitat
        secondary_properties:
        - bridge
        repeat:
          min: 1
          max: 1
        variants:
        - id: spread
          weight: 1
          cells:
          - ◢██◣
          - ' ╲╱ '
          - ████
          - █☉██
          - ████
          - ' ╱╲ '
          - ◥██◤
        - id: folded
          weight: 1
          cells:
          - '    '
          - ◢██◣
          - ████
          - █◇██
          - ████
          - ◥██◤
          - '    '
      - id: lance
        name: Lance
        primary_property: main_gun
        secondary_properties:
        - weapons
        repeat:
          min: 1
          max: 1
        variants:
        - id: needle
          weight: 1
          cells:
          - '     '
          - '     '
          - '  ─▙ '
          - ──█▓▶
          - '  ─▛ '
          - '     '
          - '     '
        - id: fork
          weight: 1
          cells:
          - '     '
          - '     '
          - '─▓█▙ '
          - ─██▓▶
          - '─▓█▛ '
          - '     '
          - '     '
      structure_lengths:
        fusion_bell: 1
        engine_swell: 1
        diamond_radiators: 5
        habitat_petals: 1
        lance: 1
    - id: medium
      name: Medium
      sections:
      - id: fusion_bell
        name: Fusion Bell
        primary_property: thrusters
        secondary_properties:
        - reactor
        repeat:
          min: 1
          max: 1
        variants:
        - id: focused
          weight: 1
          cells:
          - '   '
          - ' y '
          - y█▓
          - ' y '
          - '   '
        - id: hot
          weight: 1
          cells:
          - ' y '
          - 'y▟ '
          - y█▓
          - 'y▜ '
          - ' y '
      - id: engine_swell
        name: Engine Swell
        primary_property: spindrive
        secondary_properties:
        - reactor
        repeat:
          min: 1
          max: 1
        variants:
        - id: swell
          weight: 1
          cells:
          - ◢█◣
          - ▓█▓
          - █▒█
          - ▓█▓
          - ◥█◤
        - id: veined
          weight: 1
          cells:
          - ◢█◣
          - ▓█▓
          - █▒█
          - ▓█▓
          - ◥█◤
      - id: diamond_radiators
        name: Diamond Radiators
        primary_property: radiator
        secondary_properties:
        - hull
        repeat:
          min: 1
          max: 6
        variants:
        - id: open
          weight: 1
          cells:
          - ' ╲ '
          - ┌─┐
          - │▒│
          - └─┘
          - ' ╱ '
        - id: folded
          weight: 1
          cells:
          - ' │ '
          - ┌─┐
          - │◇│
          - └─┘
          - ' │ '
      - id: habitat_petals
        name: Habitat Petals
        primary_property: habitat
        secondary_properties:
        - bridge
        repeat:
          min: 1
          max: 1
        variants:
        - id: spread
          weight: 1
          cells:
          - ' ╲ '
          - ███
          - █☉█
          - ███
          - ' ╱ '
        - id: folded
          weight: 1
          cells:
          - ◢█◣
          - ███
          - █◇█
          - ███
          - ◥█◤
      - id: lance
        name: Lance
        primary_property: main_gun
        secondary_properties:
        - weapons
        repeat:
          min: 1
          max: 1
        variants:
        - id: needle
          weight: 1
          cells:
          - '    '
          - '  ─ '
          - ──█▶
          - '  ─ '
          - '    '
        - id: fork
          weight: 1
          cells:
          - '    '
          - '─▓█ '
          - ─██▶
          - '─▓█ '
          - '    '
      structure_lengths:
        fusion_bell: 1
        engine_swell: 1
        diamond_radiators: 5
        habitat_petals: 1
        lance: 1
    - id: compact
      name: Compact
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - ' ▴'
          - y█
          - ' ▾'
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 11
        variants:
        - id: fins
          weight: 1
          cells:
          - ◢█
          - ██
          - ◥█
        - id: petal
          weight: 1
          cells:
          - ▀█
          - █◇
          - ▄█
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: lance
          weight: 1
          cells:
          - '   '
          - ─█▶
          - '   '
      structure_lengths:
        drive: 1
        body: 6
        prow: 1
  vertical:
    name: Vertical
    axis: vertical
    canonical_facing: up
    mirror_facing: down
    tiers:
    - id: full
      name: Full Detail
      sections:
      - id: fusion_bell
        name: Fusion Bell
        primary_property: thrusters
        secondary_properties:
        - reactor
        repeat:
          min: 1
          max: 1
        variants:
        - id: focused
          weight: 1
          cells:
          - ║║    ▓▓    ║║
          - yy  yy██yy  yy
        - id: hot
          weight: 1
          cells:
          - ║║    ▓▓    ║║
          - yyyy▜▜██▛▛yyyy
      - id: engine_swell
        name: Engine Swell
        primary_property: spindrive
        secondary_properties:
        - reactor
        repeat:
          min: 1
          max: 1
        variants:
        - id: swell
          weight: 1
          cells:
          - '  ◢◢▓▓██▓▓◣◣  '
          - ◀◀████▒▒████▶▶
        - id: veined
          weight: 1
          cells:
          - '  ◢◢▓▓██▓▓◣◣  '
          - RR████▒▒████▶▶
      - id: diamond_radiators
        name: Diamond Radiators
        primary_property: radiator
        secondary_properties:
        - hull
        repeat:
          min: 1
          max: 6
        variants:
        - id: open
          weight: 1
          cells:
          - '    ┌┌──┐┐    '
          - ██╱╱││▒▒││╲╲██
        - id: folded
          weight: 1
          cells:
          - '    ┌┌──┐┐    '
          - ◀◀──││◇◇││──▶▶
      - id: habitat_petals
        name: Habitat Petals
        primary_property: habitat
        secondary_properties:
        - bridge
        repeat:
          min: 1
          max: 1
        variants:
        - id: spread
          weight: 1
          cells:
          - ◢◢  ██████  ◣◣
          - ██╱╱██☉☉██╲╲██
        - id: folded
          weight: 1
          cells:
          - '  ◢◢██████◣◣  '
          - '  ████◇◇████  '
      - id: lance
        name: Lance
        primary_property: main_gun
        secondary_properties:
        - weapons
        repeat:
          min: 1
          max: 1
        variants:
        - id: needle
          weight: 1
          cells:
          - '      ▴▴      '
          - '    ││██││    '
          - '      ││      '
        - id: fork
          weight: 1
          cells:
          - '      ▴▴      '
          - '    ██████    '
          - '    ││││││    '
      structure_lengths:
        fusion_bell: 1
        engine_swell: 1
        diamond_radiators: 6
        habitat_petals: 1
        lance: 1
    - id: medium
      name: Medium
      sections:
      - id: fusion_bell
        name: Fusion Bell
        primary_property: thrusters
        secondary_properties:
        - reactor
        repeat:
          min: 1
          max: 1
        variants:
        - id: focused
          weight: 1
          cells:
          - '    ▓▓    '
          - '    yy    '
        - id: hot
          weight: 1
          cells:
          - '    ▓▓    '
          - '  yyyyyy  '
      - id: engine_swell
        name: Engine Swell
        primary_property: spindrive
        secondary_properties:
        - reactor
        repeat:
          min: 1
          max: 1
        variants:
        - id: swell
          weight: 1
          cells:
          - ◢◢▓▓██▓▓◣◣
          - ◥◥▓▓██▓▓◤◤
        - id: veined
          weight: 1
          cells:
          - ◢◢▓▓██▓▓◣◣
          - ◥◥▓▓██▓▓◤◤
      - id: diamond_radiators
        name: Diamond Radiators
        primary_property: radiator
        secondary_properties:
        - hull
        repeat:
          min: 1
          max: 6
        variants:
        - id: open
          weight: 1
          cells:
          - '  ┌┌──┐┐  '
          - '  └└──┘┘  '
        - id: folded
          weight: 1
          cells:
          - '  ┌┌──┐┐  '
          - '  └└──┘┘  '
      - id: habitat_petals
        name: Habitat Petals
        primary_property: habitat
        secondary_properties:
        - bridge
        repeat:
          min: 1
          max: 1
        variants:
        - id: spread
          weight: 1
          cells:
          - '  ██████  '
          - '  ██████  '
        - id: folded
          weight: 1
          cells:
          - ◢◢██████◣◣
          - ◥◥██████◤◤
      - id: lance
        name: Lance
        primary_property: main_gun
        secondary_properties:
        - weapons
        repeat:
          min: 1
          max: 1
        variants:
        - id: needle
          weight: 1
          cells:
          - '    ▴▴    '
          - '    ││    '
        - id: fork
          weight: 1
          cells:
          - '    ▴▴    '
          - '  ▓▓██▓▓  '
      structure_lengths:
        fusion_bell: 1
        engine_swell: 1
        diamond_radiators: 6
        habitat_petals: 1
        lance: 1
    - id: compact
      name: Compact
      sections:
      - id: drive
        name: Drive
        primary_property: thrusters
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: drive
          weight: 1
          cells:
          - ◀◀██▶▶
      - id: body
        name: Body
        primary_property: hull
        secondary_properties:
        - armor
        repeat:
          min: 1
          max: 11
        variants:
        - id: fins
          weight: 1
          cells:
          - ██████
        - id: petal
          weight: 1
          cells:
          - ██◇◇██
      - id: prow
        name: Prow
        primary_property: weapons
        secondary_properties: []
        repeat:
          min: 1
          max: 1
        variants:
        - id: lance
          weight: 1
          cells:
          - '  ▴▴  '
          - '  ││  '
      structure_lengths:
        drive: 1
        body: 11
        prow: 1
